### ISSUE TITLE
缺少完善的文档

### ISSUE THREAD

**Issue by yangweijie** [iszsw/curd#1]
文档缺失，
配置里只有路由前缀，
生成菜单后的地址一般是什么样？如何访问 只能看demo才知道是curd/page/index?_table=z_user，生成菜单感觉有歧义，只是生成路由映射吧，所有的数据表配置保存在配置里，不透明。
然后上传改了之后上传报错403 
去看源码suface 才知道要返回 

```
echo json_encode(
    [
        'code' => 0,
        'msg'  => 'success',
        'data' => [
            'url'  => 'http://q1.qlogo.cn/g?b=qq&nk=191587'.rand(100, 999).'&s=640',
        ],
    ], JSON_UNESCAPED_UNICODE
);
```
这种格式，
相当于上传后的字段只能存路径，像一般cms是上传后插入附件表md5 去重，返回id,展示用id获取路径的。

**Comment by iszsw** [comment]
1.内部系统中生成菜单是会真实生成菜单&nbsp; 这个curd包中这个功能被删除了 只是返回了一个访问地址&nbsp;&nbsp;
2.图片上传 需要自己自定义存本地或者oss 返回图片地址，适合于大多数场景，不过如果你要存id可以在图片url上携带一个‘id’参数
这个工具刚刚弄完&nbsp; 文档也在完善&nbsp; &nbsp;可能还存在一些问题&nbsp; 欢迎反馈 我这边也会马上处理




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iszsw/curd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月16日(星期五) 上午10:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[iszsw/curd] 缺少完善的文档 (#1)





 
文档缺失，
 配置里只有路由前缀，
 生成菜单后的地址一般是什么样？如何访问 只能看demo才知道是curd/page/index?_table=z_user，生成菜单感觉有歧义，只是生成路由映射吧，所有的数据表配置保存在配置里，不透明。
 然后上传改了之后上传报错403
 去看源码suface 才知道要返回
 echo json_encode(     [         'code' =&gt; 0,         'msg'  =&gt; 'success',         'data' =&gt; [             'url'  =&gt; 'http://q1.qlogo.cn/g?b=qq&amp;nk=191587'.rand(100, 999).'&amp;s=640',         ],     ], JSON_UNESCAPED_UNICODE );  
这种格式，
 相当于上传后的字段只能存路径，像一般cms是上传后插入附件表md5 去重，返回id,展示用id获取路径的。
