### ISSUE TITLE
1,数值数据转换为字符串输出会导致排序时按字典序排列 2,分页功能无效

### ISSUE THREAD

**Issue by iruska-divine** [iszsw/curd#2]
https://github.com/iszsw/curd/blob/506468ba24d70543d506cbca7a9c1257f45b7760/src/lib/ResolveTable.php#L505

**Comment by iruska-divine** [comment]
![01](https://user-images.githubusercontent.com/20485384/155246035-e174861b-f822-4d63-9bcb-c0a1707d75c9.png)
![02](https://user-images.githubusercontent.com/20485384/155246053-becce053-a353-4b39-a56f-39cfd2601e74.png)

**Comment by iszsw** [comment]
感谢反馈  确实有问题   我将尽快修复

**Comment by iszsw** [comment]
已处理
