### ISSUE TITLE
curd如何使用可编辑开关？

### ISSUE THREAD

**Issue by Ivaneus** [iszsw/curd#5]
数据库表在tinyint字段下应该如何配置，定义开关修改键值为0或者1？
直接采用默认设置无法修改数据

**Comment by iszsw** [comment]
switch 可以设置 active-value和inactive-value 开关的值  现在默认是true和false  下一个版本修改默认值为0 1

**Comment by Ivaneus** [comment]
是在表格扩展中自定义索引么？似乎定义了这两个值仍然无法修改。能否在演示站点中提供该组件的详细使用样例

**Comment by iszsw** [comment]
如果你是修改表格里面的值  可以在字段信息->修改字段 -> 自定义 选择表格 里面有个表格扩展 设置这两个值

**Comment by Ivaneus** [comment]
仍然不可控，按钮触发提示值未修改。表单测试使用扩展后可以修改数据库的字段内容，但是修改后的数据没有同步回馈到表单中

**Comment by iszsw** [comment]
最简单的方法就是在 字段信息->修改字段 -> 自定义 选择 '保存' 保存格式化里面添加一个自定义方法  每次修改数据库当前字段前都会请求该方法  在接下来的v3版本里面会修改统一这些规范

**Comment by Ivaneus** [comment]
静待V3版本更完善的系统和使用文档，谢谢。
